### PR TITLE
Text Has Pretty Colors

### PR DESCRIPTION
**Pull request by natehole**
This might not be desired but if it is here ya go. It can be tweaked for different results.

Added 3 new functions to change font and toolbar color to be similar to the color generated. I formatted the file once and it seems to have added some spaces where vscode wanted them.

here is an example of the font color changes and the toolbar heading changes
image

### CODE REVIEW

**Comment by rogue-cyborg** [comment]
@natehole For the font color, I'm not sure blending it with the colors is a great idea for accessibility. We want to make sure the contrast ratio is sufficient and it doesn't look like that text will do so. You can see some examples of this at [WebAIM](https://webaim.org/resources/contrastchecker/) and if the ratios pass, we can merge it.

However, I do like the idea of changing the toolbar color to make the palette swatch color.

**Comment by natehole** [comment]
Thanks, I'll take a look at the link you posted. If I am unable to improve the text color readability I will revert to using black and white but regardless I will keep the toolbar color change.

**Comment by natehole** [comment]
@rogue-cyborg reverted to black and white text, I changed the lock and regenerate to match. I couldn't think of a not hacky solution to determine a good readable font color that is similar to the swatch. Let me know if there is anything you would like for me to change.

Example of the current state. I think it can be jarring looking at the locks and reloads change form black to white but it does improve clearness on particularly light swatches. It is an icon however so maybe it should stay one color.

image

**Comment by rogue-cyborg** [comment]
@natehole 

Agreed, the white and black is jarring. I'm going to leave this open for the time being to see if anyone else has an idea to get a good solution.

My only thought so far is that we could do the following:
1. Create a function that calculates a shade or tint using [this logic](https://stackoverflow.com/a/31325812).
2. Call those shade/tint functions in a loop that calculates the result and checks the contrast. If the contrast isn't good enough, it needs to retry. Eventually, it'll reach black or white if the contrast isn't good enough for any of the other values.

**Comment by natehole** [comment]
I can work on this tomorrow. I'm thinking the lock and regenerate should correlate with light and dark mode. Changing font color using the hue and tint methods posted should be easy to implement

**Comment by rogue-cyborg** [comment]
@natehole If you use the hue/tint methods for the font color, I'm guessing it would look good to use that method for the lock/refresh toolbar too.

**Comment by natehole** [comment]
Status update, text and icon colors respond to swatch color. I am going to work on this later to see if I can achieve better results. Right now I add/subtract 50 to the 1 to 2 strongest colors.

I attempted a solution of recursively tinting/shading a color to a passable contrast but almost every color ended up just off of white or black.

Output when adding/subtracting to white or black based off of swatch color
image

Output when tinting/shading from swatch color to an appropriate contrast.
image

**Comment by rogue-cyborg** [comment]
Hmm, in that case I think we should leave it as-is. The original contrast wasn't following accessibility and the other solutions here would be better off as just the white text on the original opaque black background.

**Pull request closed without merging**
